language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t outlawtorn/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true outlawtorn/docker-react npm run test -- --coverage