FROM node:16-alpine

USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
RUN chmod 777 /home/node/app
 
CMD ["npm", "run", "start"]